from datetime import datetime
import json

from database.models import AuditLog, RecoveryAction, RecoveryCase


def remove_legacy_generated_checkout_cases(db):
    """Remove the exact 100-event range generated by the retired demo path."""
    legacy_cases = (
        db.query(RecoveryCase.case_id)
        .filter(
            RecoveryCase.recovery_type == "CHECKOUT_ABANDONMENT",
            RecoveryCase.case_id >= "CHK-REC-CHK-100000",
            RecoveryCase.case_id <= "CHK-REC-CHK-100099",
            RecoveryCase.source_event_id >= "CHK-100000",
            RecoveryCase.source_event_id <= "CHK-100099",
            RecoveryCase.source_context.notlike("%seeded_demo%"),
        )
        .all()
    )
    case_ids = [case_id for (case_id,) in legacy_cases]
    if not case_ids:
        return 0

    db.query(AuditLog).filter(AuditLog.case_id.in_(case_ids)).delete(
        synchronize_session=False,
    )
    db.query(RecoveryAction).filter(RecoveryAction.case_id.in_(case_ids)).delete(
        synchronize_session=False,
    )
    db.query(RecoveryCase).filter(RecoveryCase.case_id.in_(case_ids)).delete(
        synchronize_session=False,
    )
    db.flush()
    return len(case_ids)


def create_checkout_cases(db, checkout_events):
    remove_legacy_generated_checkout_cases(db)
    detected_cases = detect_checkout_risk(checkout_events)
    created_cases = []

    for data in detected_cases:
        checkout_id = data["checkout_id"]
        case_id = data["case_id"]

        existing = (
            db.query(RecoveryCase)
            .filter(
                (RecoveryCase.case_id == case_id)
                | (RecoveryCase.source_event_id == checkout_id)
            )
            .first()
        )

        # Do not count existing cases as newly detected.
        if existing:
            continue

        case = RecoveryCase(
            case_id=case_id,
            customer_id=data["customer_id"],
            payment_id=checkout_id,
            amount_at_risk=data["amount_at_risk"],
            risk_score=data["risk_score"],
            recovery_probability=data["risk_score"],
            expected_recovery=data["expected_recovery"],
            status="AT_RISK",
            recovery_type="CHECKOUT_ABANDONMENT",
            source_event_id=checkout_id,
            source_context=json.dumps(
                {
                    "minutes_since_abandonment": data[
                        "minutes_since_abandonment"
                    ],
                    "payment_attempted": data["payment_attempted"],
                    "currency": data.get("currency", "INR"),
                    "detected_at": data["detected_at"].isoformat(),
                },
                sort_keys=True,
            ),
        )

        db.add(case)
        created_cases.append(case)

    db.commit()
    return created_cases


def detect_checkout_risk(checkout_events):
    cases = []

    for checkout in checkout_events:
        amount = checkout["amount"]
        minutes = checkout["minutes_since_abandonment"]

        if amount < 999:
            continue

        risk_points = 50

        if amount >= 9999:
            risk_points += 20

        if minutes <= 60:
            risk_points += 20

        if checkout["payment_attempted"]:
            risk_points += 10

        risk_score = min(risk_points, 100) / 100

        cases.append(
            {
                "case_id": f"CHK-REC-{checkout['checkout_id']}",
                "checkout_id": checkout["checkout_id"],
                "customer_id": checkout["customer_id"],
                "amount_at_risk": amount,
                "risk_score": risk_score,
                "expected_recovery": round(
                    amount * risk_score,
                    2,
                ),
                "recovery_type": "CHECKOUT_ABANDONMENT",
                "payment_attempted": checkout["payment_attempted"],
                "minutes_since_abandonment": minutes,
                "detected_at": datetime.utcnow(),
                "currency": checkout.get("currency", "INR"),
            }
        )

    return cases
